using TopSpeed.Input.Devices.Controller;
using TopSpeed.Localization;

namespace TopSpeed.Input
{
    internal static class InputDisplayText
    {
        public static string Key(InputKey key)
        {
            if ((int)key <= 0)
                return LocalizationService.Translate(LocalizationService.Mark("none"));

            return key switch
            {
                InputKey.Unknown => LocalizationService.Translate(LocalizationService.Mark("Unknown")),
                InputKey.Escape => LocalizationService.Translate(LocalizationService.Mark("Escape")),
                InputKey.Minus => LocalizationService.Translate(LocalizationService.Mark("Minus")),
                InputKey.Equals => LocalizationService.Translate(LocalizationService.Mark("Equals")),
                InputKey.Back => LocalizationService.Translate(LocalizationService.Mark("Backspace")),
                InputKey.Tab => LocalizationService.Translate(LocalizationService.Mark("Tab")),
                InputKey.LeftBracket => LocalizationService.Translate(LocalizationService.Mark("Left bracket")),
                InputKey.RightBracket => LocalizationService.Translate(LocalizationService.Mark("Right bracket")),
                InputKey.Return => LocalizationService.Translate(LocalizationService.Mark("Enter")),
                InputKey.LeftControl => LocalizationService.Translate(LocalizationService.Mark("Left Control")),
                InputKey.Semicolon => LocalizationService.Translate(LocalizationService.Mark("Semicolon")),
                InputKey.Apostrophe => LocalizationService.Translate(LocalizationService.Mark("Apostrophe")),
                InputKey.Grave => LocalizationService.Translate(LocalizationService.Mark("Grave")),
                InputKey.LeftShift => LocalizationService.Translate(LocalizationService.Mark("Left Shift")),
                InputKey.Backslash => LocalizationService.Translate(LocalizationService.Mark("Backslash")),
                InputKey.Slash => LocalizationService.Translate(LocalizationService.Mark("Slash")),
                InputKey.RightShift => LocalizationService.Translate(LocalizationService.Mark("Right Shift")),
                InputKey.Multiply => LocalizationService.Translate(LocalizationService.Mark("Multiply")),
                InputKey.LeftAlt => LocalizationService.Translate(LocalizationService.Mark("Left Alt")),
                InputKey.Space => LocalizationService.Translate(LocalizationService.Mark("Space")),
                InputKey.Capital => LocalizationService.Translate(LocalizationService.Mark("Caps Lock")),
                InputKey.NumberLock => LocalizationService.Translate(LocalizationService.Mark("Num Lock")),
                InputKey.ScrollLock => LocalizationService.Translate(LocalizationService.Mark("Scroll Lock")),
                InputKey.Subtract => LocalizationService.Translate(LocalizationService.Mark("Subtract")),
                InputKey.Add => LocalizationService.Translate(LocalizationService.Mark("Add")),
                InputKey.Decimal => LocalizationService.Translate(LocalizationService.Mark("Decimal")),
                InputKey.Oem102 => LocalizationService.Translate(LocalizationService.Mark("OEM 102")),
                InputKey.Kana => LocalizationService.Translate(LocalizationService.Mark("Kana")),
                InputKey.AbntC1 => LocalizationService.Translate(LocalizationService.Mark("ABNT C1")),
                InputKey.Convert => LocalizationService.Translate(LocalizationService.Mark("Convert")),
                InputKey.NoConvert => LocalizationService.Translate(LocalizationService.Mark("No Convert")),
                InputKey.Yen => LocalizationService.Translate(LocalizationService.Mark("Yen")),
                InputKey.AbntC2 => LocalizationService.Translate(LocalizationService.Mark("ABNT C2")),
                InputKey.NumberPadEquals => LocalizationService.Translate(LocalizationService.Mark("Numpad Equals")),
                InputKey.PreviousTrack => LocalizationService.Translate(LocalizationService.Mark("Previous Track")),
                InputKey.AT => LocalizationService.Translate(LocalizationService.Mark("At")),
                InputKey.Colon => LocalizationService.Translate(LocalizationService.Mark("Colon")),
                InputKey.Underline => LocalizationService.Translate(LocalizationService.Mark("Underline")),
                InputKey.Kanji => LocalizationService.Translate(LocalizationService.Mark("Kanji")),
                InputKey.Stop => LocalizationService.Translate(LocalizationService.Mark("Stop")),
                InputKey.AX => LocalizationService.Translate(LocalizationService.Mark("AX")),
                InputKey.Unlabeled => LocalizationService.Translate(LocalizationService.Mark("Unlabeled")),
                InputKey.NextTrack => LocalizationService.Translate(LocalizationService.Mark("Next Track")),
                InputKey.NumberPadEnter => LocalizationService.Translate(LocalizationService.Mark("Numpad Enter")),
                InputKey.RightControl => LocalizationService.Translate(LocalizationService.Mark("Right Control")),
                InputKey.Mute => LocalizationService.Translate(LocalizationService.Mark("Mute")),
                InputKey.Calculator => LocalizationService.Translate(LocalizationService.Mark("Calculator")),
                InputKey.PlayPause => LocalizationService.Translate(LocalizationService.Mark("Play/Pause")),
                InputKey.MediaStop => LocalizationService.Translate(LocalizationService.Mark("Media Stop")),
                InputKey.VolumeDown => LocalizationService.Translate(LocalizationService.Mark("Volume Down")),
                InputKey.VolumeUp => LocalizationService.Translate(LocalizationService.Mark("Volume Up")),
                InputKey.WebHome => LocalizationService.Translate(LocalizationService.Mark("Web Home")),
                InputKey.NumberPadComma => LocalizationService.Translate(LocalizationService.Mark("Numpad Comma")),
                InputKey.Divide => LocalizationService.Translate(LocalizationService.Mark("Divide")),
                InputKey.PrintScreen => LocalizationService.Translate(LocalizationService.Mark("Print Screen")),
                InputKey.RightAlt => LocalizationService.Translate(LocalizationService.Mark("Right Alt")),
                InputKey.Pause => LocalizationService.Translate(LocalizationService.Mark("Pause")),
                InputKey.Home => LocalizationService.Translate(LocalizationService.Mark("Home")),
                InputKey.Up => LocalizationService.Translate(LocalizationService.Mark("Up")),
                InputKey.PageUp => LocalizationService.Translate(LocalizationService.Mark("Page Up")),
                InputKey.Left => LocalizationService.Translate(LocalizationService.Mark("Left")),
                InputKey.Right => LocalizationService.Translate(LocalizationService.Mark("Right")),
                InputKey.End => LocalizationService.Translate(LocalizationService.Mark("End")),
                InputKey.Down => LocalizationService.Translate(LocalizationService.Mark("Down")),
                InputKey.PageDown => LocalizationService.Translate(LocalizationService.Mark("Page Down")),
                InputKey.Insert => LocalizationService.Translate(LocalizationService.Mark("Insert")),
                InputKey.Delete => LocalizationService.Translate(LocalizationService.Mark("Delete")),
                InputKey.LeftWindowsKey => LocalizationService.Translate(LocalizationService.Mark("Left Windows")),
                InputKey.RightWindowsKey => LocalizationService.Translate(LocalizationService.Mark("Right Windows")),
                InputKey.Applications => LocalizationService.Translate(LocalizationService.Mark("Applications")),
                InputKey.Power => LocalizationService.Translate(LocalizationService.Mark("Power")),
                InputKey.Sleep => LocalizationService.Translate(LocalizationService.Mark("Sleep")),
                InputKey.Wake => LocalizationService.Translate(LocalizationService.Mark("Wake")),
                InputKey.WebSearch => LocalizationService.Translate(LocalizationService.Mark("Web Search")),
                InputKey.WebFavorites => LocalizationService.Translate(LocalizationService.Mark("Web Favorites")),
                InputKey.WebRefresh => LocalizationService.Translate(LocalizationService.Mark("Web Refresh")),
                InputKey.WebStop => LocalizationService.Translate(LocalizationService.Mark("Web Stop")),
                InputKey.WebForward => LocalizationService.Translate(LocalizationService.Mark("Web Forward")),
                InputKey.WebBack => LocalizationService.Translate(LocalizationService.Mark("Web Back")),
                InputKey.MyComputer => LocalizationService.Translate(LocalizationService.Mark("My Computer")),
                InputKey.Mail => LocalizationService.Translate(LocalizationService.Mark("Mail")),
                InputKey.MediaSelect => LocalizationService.Translate(LocalizationService.Mark("Media Select")),
                _ => key.ToString()
            };
        }

        public static string Axis(AxisOrButton axis)
        {
            return axis switch
            {
                AxisOrButton.AxisNone => LocalizationService.Translate(LocalizationService.Mark("none")),
                AxisOrButton.AxisXNeg => LocalizationService.Translate(LocalizationService.Mark("X minus")),
                AxisOrButton.AxisXPos => LocalizationService.Translate(LocalizationService.Mark("X plus")),
                AxisOrButton.AxisYNeg => LocalizationService.Translate(LocalizationService.Mark("Y minus")),
                AxisOrButton.AxisYPos => LocalizationService.Translate(LocalizationService.Mark("Y plus")),
                AxisOrButton.AxisZNeg => LocalizationService.Translate(LocalizationService.Mark("Z minus")),
                AxisOrButton.AxisZPos => LocalizationService.Translate(LocalizationService.Mark("Z plus")),
                AxisOrButton.AxisRxNeg => LocalizationService.Translate(LocalizationService.Mark("RX minus")),
                AxisOrButton.AxisRxPos => LocalizationService.Translate(LocalizationService.Mark("RX plus")),
                AxisOrButton.AxisRyNeg => LocalizationService.Translate(LocalizationService.Mark("RY minus")),
                AxisOrButton.AxisRyPos => LocalizationService.Translate(LocalizationService.Mark("RY plus")),
                AxisOrButton.AxisRzNeg => LocalizationService.Translate(LocalizationService.Mark("RZ minus")),
                AxisOrButton.AxisRzPos => LocalizationService.Translate(LocalizationService.Mark("RZ plus")),
                AxisOrButton.AxisSlider1Neg => LocalizationService.Translate(LocalizationService.Mark("Slider 1 minus")),
                AxisOrButton.AxisSlider1Pos => LocalizationService.Translate(LocalizationService.Mark("Slider 1 plus")),
                AxisOrButton.AxisSlider2Neg => LocalizationService.Translate(LocalizationService.Mark("Slider 2 minus")),
                AxisOrButton.AxisSlider2Pos => LocalizationService.Translate(LocalizationService.Mark("Slider 2 plus")),
                AxisOrButton.Button1 => LocalizationService.Translate(LocalizationService.Mark("Button 1")),
                AxisOrButton.Button2 => LocalizationService.Translate(LocalizationService.Mark("Button 2")),
                AxisOrButton.Button3 => LocalizationService.Translate(LocalizationService.Mark("Button 3")),
                AxisOrButton.Button4 => LocalizationService.Translate(LocalizationService.Mark("Button 4")),
                AxisOrButton.Button5 => LocalizationService.Translate(LocalizationService.Mark("Button 5")),
                AxisOrButton.Button6 => LocalizationService.Translate(LocalizationService.Mark("Button 6")),
                AxisOrButton.Button7 => LocalizationService.Translate(LocalizationService.Mark("Button 7")),
                AxisOrButton.Button8 => LocalizationService.Translate(LocalizationService.Mark("Button 8")),
                AxisOrButton.Button9 => LocalizationService.Translate(LocalizationService.Mark("Button 9")),
                AxisOrButton.Button10 => LocalizationService.Translate(LocalizationService.Mark("Button 10")),
                AxisOrButton.Button11 => LocalizationService.Translate(LocalizationService.Mark("Button 11")),
                AxisOrButton.Button12 => LocalizationService.Translate(LocalizationService.Mark("Button 12")),
                AxisOrButton.Button13 => LocalizationService.Translate(LocalizationService.Mark("Button 13")),
                AxisOrButton.Button14 => LocalizationService.Translate(LocalizationService.Mark("Button 14")),
                AxisOrButton.Button15 => LocalizationService.Translate(LocalizationService.Mark("Button 15")),
                AxisOrButton.Button16 => LocalizationService.Translate(LocalizationService.Mark("Button 16")),
                AxisOrButton.Pov1 => LocalizationService.Translate(LocalizationService.Mark("POV 1 up")),
                AxisOrButton.Pov2 => LocalizationService.Translate(LocalizationService.Mark("POV 1 right")),
                AxisOrButton.Pov3 => LocalizationService.Translate(LocalizationService.Mark("POV 1 down")),
                AxisOrButton.Pov4 => LocalizationService.Translate(LocalizationService.Mark("POV 1 left")),
                AxisOrButton.Pov5 => LocalizationService.Translate(LocalizationService.Mark("POV 2 up")),
                AxisOrButton.Pov6 => LocalizationService.Translate(LocalizationService.Mark("POV 2 right")),
                AxisOrButton.Pov7 => LocalizationService.Translate(LocalizationService.Mark("POV 2 down")),
                AxisOrButton.Pov8 => LocalizationService.Translate(LocalizationService.Mark("POV 2 left")),
                _ => axis.ToString()
            };
        }
    }
}
